### ISSUE TITLE
Transformatin image

### ISSUE THREAD

**Issue by ArtyomPro** [radimspetlik/hr-cnn#1]
Hello. Interested in your project. But I'm having trouble:
You are loading an image from the database. I want to run your model through my video. But I can't do that because I don't understand how the facial image is being transformed before it's fed into the neural network.

**Comment by radimspetlik** [comment]
Hi, for some reason, the github doesn't send me notifications. Realized now. Did you solve it, please?

**Comment by radimspetlik** [comment]
Hi, I am closing this issue since you did not respond (of course, my fault, cuz I did not respond for a much longer period, sorry and feel free to re-open, I should respond faster...)
