### ISSUE TITLE
ImportError: libavutil.so.55: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DogeFlow** [radimspetlik/hr-cnn#2]
Hello,
         I followed the instructions to complete all the steps.But when I do the test, i met this problem:

         ImportError: libavutil.so.55: cannot open shared object file: No such file or directory.

         How can i solve it ?

**Comment by radimspetlik** [comment]
Hi, for some reason, the github doesn't send me notifications. Realized now. Did you solve it, please?

**Comment by HuaLi2333** [comment]
I also encountered this problem. I don't know if it's due to the version problem.Do you have any suggestions?

**Comment by radimspetlik** [comment]
@HuaLi2333 
Hi, I'm going to investigate... Hopefully next week...

**Comment by HuaLi2333** [comment]
Thank you. I am very interested in your research and look forward to your investigation.

**Comment by amberhappy** [comment]
I also meet this problem....

**Comment by radimspetlik** [comment]
So, I updated the instructions; could you please check if the problem persists?

**Comment by amberhappy** [comment]
> So, I updated the instructions; could you please check if the problem persists?

Thank you for updating, but the problem still persists, details as flollows:

/home/lq/anaconda3/envs/hr-cnn/bin/python /home/lq/Desktop/new/hr-cnn-master/test-evaluation.py
('extractor_model_path:', 'data/models/08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best')
[INFO]Performing experiments on ecg-fitness database, protocol test.
[INFO]Loading model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best.
[WARNING]Was not able to load state_dictionary, trying to add/remove "module."...
[INFO]Model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best loaded.
Traceback (most recent call last):
  File "/home/lq/Desktop/new/hr-cnn-master/test-evaluation.py", line 135, in <module>
    perform_experiments(dataset, 'test')
  File "/home/lq/Desktop/new/hr-cnn-master/test-evaluation.py", line 96, in perform_experiments
    faces_dir) + ' --outdir ' + str(pulse_dir) + ' --batch-size ' + str(batch_size))
  File "/home/lq/Desktop/new/hr-cnn-master/cmp/nrppg/experiments/extract_pulse_cnn.py", line 185, in main
    import bob.db.ecg_fitness
  File "/home/lq/Desktop/new/hr-cnn-master/bob/db/ecg_fitness/__init__.py", line 7, in <module>
    from models import *
  File "/home/lq/Desktop/new/hr-cnn-master/bob/db/ecg_fitness/models.py", line 15, in <module>
    import utils
  File "/home/lq/Desktop/new/hr-cnn-master/bob/db/ecg_fitness/utils.py", line 8, in <module>
    import bob.io.video
  File "/home/lq/Desktop/new/hr-cnn-master/bob/io/video/__init__.py", line 4, in <module>
    from ._library import *
ImportError: libavutil.so.55: cannot open shared object file: No such file or directory

Process finished with exit code 1

**Comment by radimspetlik** [comment]
It seems that you don't have the libav-tools library installed in your system. Try to install with _sudo apt-get install libav-tools_

**Comment by amberhappy** [comment]
> It seems that you don't have the libav-tools library installed in your system. Try to install with _sudo apt-get install libav-tools_

Thank you very much, this helps me solve the problem

**Comment by jujuran2** [comment]
sorry ,excuse me , I have the same problem with the new updated project.
 [INFO]Performing experiments on ecg-fitness database, protocol test.
[INFO]Loading model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best.
[WARNING]Was not able to load state_dictionary, trying to add/remove "module."...
[INFO]Model 08-05-2018_23-04-07-384974_arch=FaceHRNet09V4ELURGB_lr=1E-05_batch-size=300_fine_tuning_extractor_val_mae_best loaded.
Traceback (most recent call last):
  File "/home/a203/Music/hr-cnn-master/test-evaluation.py", line 128, in <module>
    perform_experiments(dataset, 'test')
  File "/home/a203/Music/hr-cnn-master/test-evaluation.py", line 89, in perform_experiments
    faces_dir) + ' --outdir ' + str(pulse_dir) + ' --batch-size ' + str(batch_size))
  File "/home/a203/Music/hr-cnn-master/cmp/nrppg/experiments/extract_pulse_cnn.py", line 185, in main
    import bob.db.ecg_fitness
  File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/__init__.py", line 7, in <module>
    from models import *
  File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/models.py", line 15, in <module>
    import utils
  File "/home/a203/Music/hr-cnn-master/bob/db/ecg_fitness/utils.py", line 8, in <module>
    import bob.io.video
  File "/home/a203/Music/hr-cnn-master/bob/io/video/__init__.py", line 4, in <module>
    from ._library import *
ImportError: libavutil.so.55: cannot open shared object file: No such file or directory

After I  install with sudo apt-get install libav-tools , the ImportError: libavutil.so.55: cannot open shared object file: No such file or directory still exists.

**Comment by radimspetlik** [comment]
@jujuran2, this is something to do with your system; It is very hard for me to debug your system... I suggest that you should check that the path to the libavutil library is in the same working environment as my python scripts...
