### ISSUE TITLE
result question

### ISSUE THREAD

**Issue by xixianli** [radimspetlik/hr-cnn#3]
I ran your source code on Github and found that it was not consistent with the results in the paper. Can you give me some guidance? Thank you！

**Comment by radimspetlik** [comment]
Hi, for some reason, the github doesn't send me notifications. Realized now. Did you solve it, please?

**Comment by radimspetlik** [comment]
I am closing this since you did not reply (of course, my fault, cuz I did not respond earlier.. sorry about that...)
